pkill -9 eNB_Process
pkill -9 eNB_Process
pkill -9 eNB_Process
pkill -9 eNB_Process
pkill -9 eNB_Process
pkill -9 eNB_Process
pkill -9 ue_Process
pkill -9 ue_Process
pkill -9 ue_Process
pkill -9 channel
